#!/bin/sh
# Atmosphere CLI Import Plugin: JavaClaw
# Generates a JavaClaw-compatible Gradle plugin project from a skill file.
#
# Install: cp import-javaclaw.sh ~/.atmosphere/plugins/
# Use:     atmosphere import --target javaclaw <skill>
#
# Contract: $1=skill_file $2=project_name $3=skill_name $4=skill_desc $5=headless

set -e

SKILL_FILE="$1"
PROJECT_NAME="$2"
SKILL_NAME="$3"
SKILL_DESC="$4"
HEADLESS="${5:-false}"

[ -z "$SKILL_FILE" ] && echo "error: no skill file provided" && exit 1
[ -z "$PROJECT_NAME" ] && PROJECT_NAME="$SKILL_NAME"

PROJECT_DIR="$PROJECT_NAME"
[ -d "$PROJECT_DIR" ] && echo "error: directory '$PROJECT_DIR' already exists" && exit 1

# Generate class name: "weather-bot" → "WeatherBot"
AGENT_CLASS=$(echo "$SKILL_NAME" | sed 's/[^a-zA-Z0-9]/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1' | tr -d ' ')
SAFE_PKG=$(echo "$SKILL_NAME" | tr '-' '_' | sed 's/[^a-z0-9_]//g')
PACKAGE="ai.javaclaw.plugins.${SAFE_PKG}"
PACKAGE_DIR=$(echo "$PACKAGE" | tr '.' '/')

# Extract tools from ## Tools section
SKILL_CONTENT=$(cat "$SKILL_FILE")
TOOLS_SECTION=$(echo "$SKILL_CONTENT" | sed -n '/^## Tools/,/^## /p' | grep '^\- ' | sed 's/^- //')

# Create project structure
mkdir -p "$PROJECT_DIR/src/main/java/$PACKAGE_DIR"
mkdir -p "$PROJECT_DIR/src/main/resources/prompts"

# Copy skill file
cp "$SKILL_FILE" "$PROJECT_DIR/src/main/resources/prompts/skill.md"

# Generate Spring AI @Tool methods from ## Tools
TOOL_METHODS=""
if [ -n "$TOOLS_SECTION" ]; then
    while IFS= read -r tool_line; do
        if echo "$tool_line" | grep -q ':'; then
            tool_name=$(echo "$tool_line" | cut -d: -f1 | tr -d ' ' | tr '[:upper:]' '[:lower:]')
            tool_desc=$(echo "$tool_line" | cut -d: -f2- | sed 's/^ *//')
        else
            tool_name=$(echo "$tool_line" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | sed 's/[^a-z0-9_]//g')
            tool_desc="$tool_line"
        fi
        method_name=$(echo "$tool_name" | awk -F_ '{for(i=1;i<=NF;i++){if(i==1)printf "%s",$i;else printf "%s",toupper(substr($i,1,1))substr($i,2)}print ""}')

        TOOL_METHODS="${TOOL_METHODS}

    @Tool(description = \"${tool_desc}\")
    public String ${method_name}(String input) {
        // TODO: implement
        return \"${tool_name} result for: \" + input;
    }"
    done <<< "$TOOLS_SECTION"
fi

TOOL_IMPORT=""
[ -n "$TOOL_METHODS" ] && TOOL_IMPORT="
import org.springframework.ai.tool.annotation.Tool;"

# Generate JavaClaw tool class (Spring AI @Tool, auto-discovered by JavaClaw)
cat > "$PROJECT_DIR/src/main/java/$PACKAGE_DIR/${AGENT_CLASS}Tools.java" <<JAVAEOF
package $PACKAGE;
${TOOL_IMPORT}
import ai.javaclaw.tools.AutoDiscoveredTool;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * ${SKILL_DESC}
 * Auto-discovered by JavaClaw when this plugin is on the classpath.
 * Generated by: atmosphere import --target javaclaw
 */
@Configuration
public class ${AGENT_CLASS}Tools {

    @Bean
    public AutoDiscoveredTool<${AGENT_CLASS}Skills> ${SAFE_PKG}Tool() {
        return new AutoDiscoveredTool<>(new ${AGENT_CLASS}Skills());
    }
}
JAVAEOF

cat > "$PROJECT_DIR/src/main/java/$PACKAGE_DIR/${AGENT_CLASS}Skills.java" <<JAVAEOF
package $PACKAGE;
${TOOL_IMPORT}
/**
 * ${SKILL_DESC}
 * These tools are available to JavaClaw's ChatClient (with all advisors and memory).
 * They are also auto-exposed via Atmosphere's MCP and A2A protocols when
 * javaclaw-atmosphere is on the classpath.
 */
public class ${AGENT_CLASS}Skills {
${TOOL_METHODS}
}
JAVAEOF

# Generate build.gradle
cat > "$PROJECT_DIR/build.gradle" <<GRADLEEOF
plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/milestone' }
}

dependencies {
    compileOnly 'ai.javaclaw:base:1.0.0-SNAPSHOT'
    compileOnly 'org.springframework.ai:spring-ai-client-chat'
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.3"
        mavenBom "org.springframework.ai:spring-ai-bom:2.0.0-SNAPSHOT"
    }
}
GRADLEEOF

# Generate auto-configuration registration
mkdir -p "$PROJECT_DIR/src/main/resources/META-INF/spring"
echo "$PACKAGE.${AGENT_CLASS}Tools" > "$PROJECT_DIR/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"

TOOL_COUNT=$(echo "$TOOLS_SECTION" | grep -c . 2>/dev/null || echo "0")
echo ""
echo "  JavaClaw plugin scaffolded at ./$PROJECT_DIR"
echo ""
echo "  Tools: $TOOL_COUNT Spring AI @Tool methods"
echo "  Class: $PACKAGE.${AGENT_CLASS}Skills"
echo ""
echo "  To use in JavaClaw:"
echo "    1. Build: cd $PROJECT_DIR && gradle build"
echo "    2. Copy JAR to JavaClaw's plugins/ directory"
echo "    3. Restart JavaClaw — tools auto-discovered"
echo ""
echo "  With Atmosphere (adds MCP + A2A):"
echo "    Tools also available in Claude Desktop, Cursor, VS Code"
